[workspace]
resolver = "2"
members = [ 
    "type_list",
    "math",
    "system",
    "r_phy", "input", "sandbox", 
]

[workspace.dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
winit = "0.29.10"
