[package]
name = "system"
version = "0.1.0"
edition = "2021"

[dependencies]
type_list = { path = "../type_list" }
math = { path = "../math" }
winit = { workspace = true }
input = { path = "../input" }
r_phy = { path = "../r_phy" }
