[package]
name = "system"
version = "0.1.0"
edition = "2021"

[dependencies]
type_kit= { path = "../type_kit" }
math = { path = "../math" }
winit = { workspace = true }
input = { path = "../input" }
graphics = { path = "../graphics" }
to_resolve = { path = "../to_resolve" }
